http_port: '80'
tg_bot_token: asd-123-asd # your telegram bot token
debug: true # enable debug mode. In debug mode the program will wirte logs in stdout and file in a human-readable format.
log_file: logs/wlbot.log # path to log file

# mikrotik devices, all fields are required
mikrotiks:
  - id: 1
    address: 172.19.1.0:80
    login: wlbot
    password: wlbot
    default_wl: wl
    is_default: true

  - id: 2
    address: 172.19.2.0:80
    login: wlbot
    password: wlbot
    default_wl: wl
    is_default: true
    
  - id: 3
    address: 172.19.3.0:80
    login: wlbot
    password: wlbot
    default_wl: wl
    is_default: false

# telegram chat settings, if you need to set a specific white list to a chat. Also you can set use_default: true to use default wl from default mikrotiks.
chat_wls:
  - chat_id: 100
    mikrotik_id: 1
    mikrotik_wl: pribor
    use_default: true

  - chat_id: 200
    mikrotik_id: 3
    mikrotik_wl: pribor
    use_default: true

  - chat_id: 300
    mikrotik_id: 3
    mikrotik_wl: pribor
    use_default: false

  - chat_id: 400
    mikrotik_id: 3
    mikrotik_wl: pribor
    use_default: false

# telegram admin chat ids
admin_chats:
  - 100
  - 200
  - 300
  - 400

# telegram admin user ids, case is important - who can add ip with subnets
admin_users:
  - anaxita
  - ilonmask